apiVersion: v1
kind: Pod
metadata:
  name: devops-pod

spec:
  containers:
    - name: web
      image: php:8.3-apache
      ports:
        - containerPort: 80

    - name: mysql
      image: mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Hello@123"
        - name: MYSQL_DATABASE
          value: "SENG_Chaokhun-db"
