# Website Load Balancer

server {
    listen 8090;

    location / {
        proxy_pass http://178.128.93.188;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# SSH Load Balancer

stream {
    upstream ssh_backend {
        server 178.128.93.188:22;
    }

    server {
        listen 22;
        proxy_pass ssh_backend;
    }
}
